### ISSUE TITLE
CPU-imLearn: AttributeError: 'AdaBoostM1' object has no attribute 'fit'

### ISSUE THREAD

**Issue by arilwan** [inbliz/gpuimlearn#1]
To reproduce:
```
>>> from cpuimlearn import AdaBoostM1
>>> X_train = [[1, 0.5], [2, 1], [1, 1], [2, 2], [1, 2.5], [2, 4.5]]
>>> y_train = [1, 1, 2, 2, 3, 3]
>>> clf = AdaBoostM1.AdaBoostM1()
AdaBoostM1.AdaBoostM1
>>> clf.fit(X_train, y_train)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AdaBoostM1' object has no attribute 'fit'
```
It appears like this class implements a `train` method instead. But then:
```
>>> clf.train(X_train, y_train)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/gpuimlearn/src/CPU-imLearn/cpuimlearn/AdaBoostM1.py", line 45, in train
    for n in range(self.num_rounds):
AttributeError: 'AdaBoostM1' object has no attribute 'num_rounds'
```
Any fix to this?

**Comment by arilwan** [comment]
I can see, this is set to 20 in module `gpuimlearn.AdaBoostM1.py
```
24        self.num_rounds = 20
````

Closing.
